plugins {
    id 'com.android.library'
}

android {
    namespace = "com.jiguang.jpush"
    compileSdk = 34

    defaultConfig {
        minSdk = 19
    }

    lint {
        disable 'InvalidPackage'
    }
}

repositories {
    google()
    mavenCentral()
    jcenter()
}

dependencies {
    implementation ('cn.jiguang.sdk:jpush:5.7.3') {
        exclude group: 'cn.jiguang.sdk', module: 'jcore'
    }
    implementation 'cn.jiguang.sdk:jcore:5.0.4'
}
